# Generated by Django 4.2.5 on 2023-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_permission_role_rolepermission_storage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='528de06fd08d448daf0cf661fdf73e7f', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='modifie_time',
            field=models.BigIntegerField(default=1694703566238),
        ),
    ]
